name: Sync to S3 and invalidate CloudFront

on:
  push:
    branches: ["main"]
    paths:
      - out/**

jobs:
  upload-to-S3:
    environment: prod
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
      # Check out the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup the AWS CLI
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync ./out s3://${{ secrets.BUCKET_NAME }}/ --delete
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.DISTRIBUTION_ID}} \
            --paths "/*"
        
